[package]
name = "otaku"
version = "0.1.0"
authors = ["Matt Valentine-House <matt@eightbitraptor.com>"]

[dependencies]
base64 = "~0.9.1"
reqwest = "~0.8.5"
sqlite = "~0.23.9"
xdg = "~2.1.0"

[dev-dependencies]
image = "~0.19.0"
nanoid = "~0.2.0"